export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  DUPLICATE_RESOURCE = 'DUPLICATE_RESOURCE',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  RATE_LIMITED = 'RATE_LIMITED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  WEDDING_ACCESS_DENIED = 'WEDDING_ACCESS_DENIED',
  // Module 06, Section 6.6: budget items auto-created from a vendor payment
  // can only be edited/deleted via the Vendor module.
  LINKED_TO_VENDOR_PAYMENT = 'LINKED_TO_VENDOR_PAYMENT',
}
